site_name: pure-python-ds
site_description: A strictly-typed, memory-optimized Data Structures and Algorithms library.
site_url: https://ParjadM.github.io/pure-python-ds/
repo_url: https://github.com/ParjadM/pure-python-ds
repo_name: ParjadM/pure-python-ds

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

nav:
  - Home: index.md
  - Linear Structures: linear.md
  - Trees: trees.md
  - Graphs: graphs.md